export default [
    {
        yearName: '2020',
        months: [
            { name: 'march',
                products: [
                  { name: 'iPad Pro',
                      status: 'released',
                      description: 'The 11-inch and 12.9-inch iPad Pro models were updated with a faster A12Z Bionic chip, a new 10MP Ultra Wide camera, a LiDAR depth scanner for improved augmented reality experiences, and more.',
                      features: [
                        'LiDAR Scanner',
                        'Trackpad support to iPadOS',
                        'A12Z Bionic chip',
                      ],
                      sources: [
                        { name: 'Apple',
                          link: 'https://www.apple.com/newsroom/2020/03/apple-unveils-new-ipad-pro-with-lidar-scanner-and-trackpad-support-in-ipados/',
                        },
                      ],
                  },
                  { name: 'Magic Keyboard',
                      status: 'released',
                      description: '',
                    },
                  { name: 'MacBook Air',
                      status: 'released',
                      description: '',
                      features: [],
                      sources: [],
                    },
                  { name: 'Mac mini',
                      status: 'released',
                      description: '',
                      features: [],
                      sources: [],
                    },
                  { name: 'Powerbeats',
                      status: 'released',
                      description: '',
                      features: [],
                      sources: [],
                    },
               ],
            },
            { name: 'april',
                products: [
                  { name: 'iPhone SE',
                    status: 'released',
                    description: '',
                    features: '',
                    sources: '',
                  },
                ],
            },
            { name: 'may',
                products: [{ name: '13" MacBook Pro', status: 'released' }],
            },
            { name: 'september',
                products: [
                  { name: 'iPhone 12 (5.4")' },
                  { name: 'iPhone 12 (6.1")' },
                  { name: 'iPhone 12 Pro (6.1")' },
                  { name: 'iPhone 12 Pro (6.7")' },
                  { name: 'Apple Watch Series 6' },
                  { name: 'AirTags' },
                  { name: 'AirPods Studio' },
                  { name: 'HomePod' },
                  { name: 'HomePod Lite' },
                  { name: 'Small Wireless Charging Pad' },
                  { name: 'iPad Air' },
                  { name: 'iPad (10.8")' },
                ],
            },
            {
                name: 'unknown',
                products: [
                    { name: 'iMac' },
                    { name: 'Apple TV' },
                    { name: 'AirPods X' },
                ],
            },
        ],
    },
    {
        yearName: '2021',
        months: [
            {
                name: 'unknown',
                products: [
                    { name: 'iPhone SE Plus' },
                    { name: 'Game Controller' },
                    { name: 'iPad Pro' },
                    { name: 'ARM MacBook' },
                    { name: 'iPad Mini (8.5")' },

                ],
            },
        ],
    },
    {
        yearName: '2022',
        months: [
            {
                name: 'unknown',
                products: [{ name: 'Apple Glass' }],
            },
        ],
    },
]
